name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python {{ system_python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: "{{ system_python_version }}"
        cache: pip
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Package
      run: |
        pyfred package
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*.alfredworkflow
