name: Publish

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read
  pull-requests: read

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python {{ system_python_version }}
      uses: actions/setup-python@v4
      with:
        python-version: "{{ system_python_version }}"

    - name: Install pyfred
      run: |
        pip install git+https://github.com/acourtneybrown/pyfred-cli@main

    - name: Package
      run: |
        pyfred package

    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v5
      env:
        GITHUB_TOKEN: ${{ '${{ secrets.GITHUB_TOKEN }}' }}

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: dist/*.alfredworkflow
        body: ${{ '${{ steps.github_release.outputs.changelog }}' }}
