name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  tests-release:
    name: Tests for release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - name: Run checks
        uses: ./.github/actions/lint
      - name: Run tests
        uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: [tests-release]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: pip
    - name: Install dependencies
      run: pip install build
    - name: Validate that tag matches committed version
      run: python script/validate_version.py --expected_version=${{ github.ref_name }}
    - name: Build
      run: python -m build
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}

  generate-docs:
    name: Generate docs
    runs-on: ubuntu-latest
    needs: [publish]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
        cache: pip
    - name: Install dependencies
      shell: bash
      run: |
        pip install -e '.' -e '.[doc]'
    - name: Generate docs
      shell: bash
      run: |
        pdoc --output-dir docs pyfred
    - uses: actions/upload-pages-artifact@v1
      with:
        path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy-docs:
    name: Deploy docs to GitHub Pages
    needs: [generate-docs]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v1
