name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  tests-release:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Run checks
        uses: ./.github/actions/lint
      - name: Run tests
        uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}

  publish:
    name: Publish package
    runs-on: ubuntu-latest
    needs: [tests-release]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: pip
    - name: Install dependencies
      run: pip install build
    - name: Validate that tag matches committed version
      run: python script/validate_version.py --expected_version=${{ github.ref_name }}
    - name: Build
      run: python -m build
    - name: Create GitHub release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_TOKEN }}
