name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches: "*"
    tags-ignore:
      - v*

permissions:
  contents: read

jobs:
  tests-push-pr:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - name: Run checks
        uses: ./.github/actions/lint
      - name: Run tests
        uses: ./.github/actions/test
        with:
          python-version: ${{ matrix.python-version }}
